package itservicesam.android.hcg_kur_manager;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import itservicesam.android.hcg_kur_manager.BodyData;

import itservicesam.android.hcg_kur_manager.BodyDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bodyDataDaoConfig;

    private final BodyDataDao bodyDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bodyDataDaoConfig = daoConfigMap.get(BodyDataDao.class).clone();
        bodyDataDaoConfig.initIdentityScope(type);

        bodyDataDao = new BodyDataDao(bodyDataDaoConfig, this);

        registerDao(BodyData.class, bodyDataDao);
    }
    
    public void clear() {
        bodyDataDaoConfig.getIdentityScope().clear();
    }

    public BodyDataDao getBodyDataDao() {
        return bodyDataDao;
    }

}
